### ISSUE TITLE
Unable to --include-package my_library

### ISSUE THREAD

**Issue by priyaradhakrishnan0** [allenai/allennlp-as-a-library-example#6]
I am able to train the model with default models

```
/Desktop/MentionDetector/allennlp-master/allennlp/allennlp-as-a-library-example-master$ allennlp train ../../tutorials/getting_started/simple_tagger.json --serialization-dir /tmp
/tutorials/getting_started
```

This goes through successfully. 
However I am unable to train including my_package

```
~/Desktop/MentionDetector/allennlp-master/allennlp/allennlp-as-a-library-example-master$ allennlp train experiments/venue_classifier.json -s /tmp/venue_output_dir  --include-package my_library
/home/kenome/anaconda3/envs/allennlp/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/kenome/anaconda3/envs/allennlp/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/kenome/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kenome/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp/run.py", line 18, in <module>
    main(prog="python -m allennlp.run")
  File "/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp/commands/__init__.py", line 62, in main
    import_submodules(package_name)
  File "/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp/common/util.py", line 256, in import_submodules
    importlib.import_module(package_name + '.' + name)
  File "/home/kenome/anaconda3/envs/allennlp/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'my_library.models.archival'
```

Here the model seems to look for 'my_library.models.archival' where as it should be looking for 'allennlp.models.archival'
 in allennlp/common/util.py", line 256, in import_submodules
    importlib.import_module(package_name + '.' + name)

PYTHONPATH is as follows
`:/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp:/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp/allennlp-as-a-library-example-master:/home/kenome/Desktop/MentionDetector/allennlp-master:/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp/allennlp`
``
Please advise.

**Comment by MaksymDel** [comment]
Try
`python -m allennlp.run train experiments/venue_classifier.json -s /tmp/your_output_dir_here --include-package my_library`.

It always works fine for me with the command above.

**Comment by priyaradhakrishnan0** [comment]
Thanks for the suggestion. But it did not work for me.
I am getting the same error with the suggested command too.
Is this a PATH issue? I mean where should 'my_library' ideally be located with respect 'allennlp'?
I have pasted my PYTHONPATH output above. Can you please look into it.
Thanks again for the suggestion.

**Comment by matt-gardner** [comment]
The problem is with your `PYTHONPATH`.  You've put `/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp/allennlp` on your `PYTHONPATH`, which means `data`, `models`, `modules`, etc. are in your global import namespace.  This confuses `pkgutil.walk_packages`, which tries to recurse on `models` and grabs the global one instead of `my_library.models`.  I'm not sure if this is a bug in `pkgutil` or just an unsupported use case, but in either event, your `PYTHONPATH` is wrong.

Run `export PYTHONPATH=/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp`, and that should be all you need.  The other directories you have shouldn't be on your `PYTHONPATH`.

**Comment by priyaradhakrishnan0** [comment]
Hi,

Sorry to say that the suggested change to have only "/home/kenome/Desktop/
MentionDetector/allennlp-master/allennlp" in PYTHONPATH , did not work.
(log #A)
I also tried refining path of my_library (log #B), running from allennlp
folder and from allennlp-as-q-library-example-master subfolder. That did
not help either (log #C)
Then I tried adding allennlp-as-a-library-example to PYTHONPATH. That also
did not help (log#D). You can see the console ouputs in the attached log
file.

I guess if you can share me the folder structure of your allennlp folder
and allennlp-as-q-library-example-master folders, and your PYTHONPATH
values, that will help a lot.

My current folder structure looks like this.

allennlp-master
|--allennlp
|   |--Commands
|   |--common
|   |--models
|   |--allennlp-as-a-library-example-master
|   |   |--experimets
|   |   |--my-library
|   |   |    |--models
|   |   |    |--predictors

and PYTHONPATH looks like this

/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp:
/home/kenome/Desktop/MentionDetector/allennlp-master/allennlp/allennlp-as-a-library-example-master:

So, I want to know where is allennlp folder placed with respect to
allennlp-as-q-library-example-master folder , and the PYTHONPATH value.

Thanks and regards,
Priya

**Comment by matt-gardner** [comment]
Your logs didn't actually get attached to the github issue from the email that you sent - can you add them here?

**Comment by matt-gardner** [comment]
I suggest you read a tutorial or two about what exactly PYTHONPATH does.  There are some decent options here: https://www.google.com/search?q=pythonpath+tutorial.  Really understanding what's going on here is going to help you a whole lot.

I'm not going to give you a tutorial in this comment, but after you've read some tutorials, the following should make sense: you need `allennlp` to be accessible on your PYTHONPATH (and _only_ `allennlp`, not any submodules, or the directory above `allennlp`).  I suggested what I did because from your initial post it looked like your directory structure was different than it actually is.  Then, with `allennlp` on your PYTHONPATH, you should run commands from the `allennlp-as-a-library-example` directory.
